### ISSUE TITLE
Nothing happends ( lol inside )

### ISSUE THREAD

**Issue by axalox** [BionicBeaver/Ubuntu#1]
i've tried your script and don't have Ubuntu 18.04 ?

**Comment by sibe39** [comment]
petit rigolo ! 

il est bien marqué que le script n'est pas utilisable pour l'instant !

**Comment by BionicBeaver** [comment]
Petit rigolo lol

Il est bien marqué au début du script qu'il n'est pas utilisable/testable pour l'instant. Tant que cette phrase est présente, il ne faut pas le tester.
